export const phraseList = [
  ["camaron que se duerme", "se lo lleva la corriente"],
  ["no por mucho madrugar", "amanece mas temprano"],
  ["A caballero nuevo", "jinete viejo"],
  ["A caballo regalado", "no le mires el diente"],
  ["A cada cerdo", "le llega su San Martín"],
  ["A cena de vino", "desayuno de agua"],
  ["A falta de pan", "buenas son tortas"],
  ["A grandes males", "grandes remedios"],
  ["A la tercera", "va la vencida"],
  ["A mal tiempo", "usa tu paraguas"],
  ["A mal tiempo", "buena cara"],
  ["A palabras necias", "oídos sordos"],
  ["Abogado juez y doctor", "cuanto más lejos mejor"],
  ["Agua de San Juan", "quita vino y no da pan"],
  ["Agua que no has de beber", "déjala correr"],
  ["Al escarabajo sus hijos", "le parecen granos de oro fino"],
  ["Al invierno lluvioso", "verano abundoso"],
  ["Al mal tiempo", "buena cara"],
  ["Al pan pan", "y al vino vino"],
  ["Al que madruga", "Dios le ayuda"],
  ["Amor con hambre", "no dura"],
  ["Aunque la mona se vista de seda", "en casa se queda"],
  ["Año nuevo", "vida nueva"],
  ["Barriga llena", "corazón contento"],
  ["Bicho malo", "nunca muere"],
  ["Bien cena quien", "bien trabaja"],
  ["Bienaventurados los borrachos", "que verán a Dios dos veces"],
  ["Caballo que vuela", "no quiere espuela"],
  ["Cada loco", "con su tema"],
  ["Cada maestrillo", "tiene su librillo"],
  ["Cada oveja", "con su pareja"],
  ["Caras vemos", "corazones no sabemos"],
  ["Casa de herrero", "cuchillo de palo"],
  ["Cielo aguado", "hierba en prado"],
  ["Cielo empedrado", "suelo mojado"],
  ["Come para vivir", "y no vivas para comer"],
  ["Come y bebe", "que la vida es breve"],
  ["Crea fama", "y acuéstate a dormir"],
  ["Cree el ladrón", "que todos son de su condición"],
  ["Cría cuervos", "y te sacarán los ojos"],
  ["Cuando amanece", "para todo el mundo amanece"],
  ["Cuando el gato está ausente", "los ratones se diviertes"],
  ["Cuando el rió suena", "agua lleva"],
  ["De oportunidades perdidas", "se encuentra llena la vida"],
  ["De tal palo", "tal astilla"],
  ["Del dicho al hecho", "hay mucho trecho"],
  ["Del árbol caído", "todos hacen leña"],
  ["Después del trabajo", "viene la alegría"],
  ["Dios aprieta", "pero no ahorca"],
  ["Dios los cría", "y ellos se juntan"],
  ["Donde fueres", "haz lo que vieres"],
  ["Dádivas y buenas razones", "ablandan piedras y corazones"],
  ["Echar por el atajo", "no siempre ahorra trabajo"],
  ["El brazo a trabajar", "la cabeza a gobernar"],
  ["El diablo", "a los suyos quiere"],
  ["El eco", "siempre tiene la última palabra"],
  ["El hábito", "no hace al monje"],
  ["El ignorante afirma", "el sabio duda y reflexiona"],
  ["El necio es atrevido", "y el sabio comedido"],
  ["El ojo del amo", "engorda el caballo"],
  ["El perro viejo", "si ladra da consejo"],
  ["El pez grande", "se come al chico"],
  ["El que a hierro mata", "a hierro muere"],
  ["El que busca", "encuentra"],
  ["El que calla", "otorga"],
  ["El que esté libre de pecado", "no sabe lo que se pierde"],
  ["El que la hace", "la paga"],
  ["El que madruga", "encuentra todo cerrado"],
  ["El que no la debe", "no la teme"],
  ["El que ríe el último", "es el que no ha entendido el chiste"],
  ["El que ríe el último", "ríe mejor"],
  ["El tiempo", "es oro"],
  ["En boca cerrada", "no entran moscas"],
  ["En la variedad", "está el gusto"],
  ["Gota a gota", "la mar se agota"],
  ["Haz bien", "y no mires a quien"],
  ["Hierba mala", "nunca muere"],
  ["Hombre precavido", "vale por dos"],
  ["La cabra siempre", "tira al monte"],
  ["La excepción", "hace la regla"],
  ["La intención", "es lo que cuenta"],
  ["La música", "amansa las fieras"],
  ["La primavera", "la fiebre altera"],
  ["La ropa sucia", "en casa se lava"],
  ["Lo barato", "sale caro"],
  ["Lo cortés", "no quita lo valiente"],
  ["Los toros", "se ven mejor desde la barrera"],
  ["Mañana", "será otro día"],
  ["Mucho ruido", "y pocas nueces"],
  ["Más claro", "no canta un gallo"],
  ["Más sabe el diablo", "por viejo que por diablo"],
  ["Más vale estar", "solo que mal acompañado"],
  ["Más vale maña", "que fuerza"],
  ["Más vale poco", "y bueno que mucho y malo"],
  ["Más vale prevenir", "que lamentar"],
  ["Más vale tarde", "porque por la mañana me duermo"],
  ["Más vale tarde", "que nunca"],
  ["Nadie es profeta", "en su tierra"],
  ["Nadie sabe lo que tiene", "hasta que ordena su cuarto"],
  ["Ningún perro", "lamiendo engorda"],
  ["No es oro", "todo lo que reluce"],
  ["No hay caballo", "por bueno que sea que no tropiece"],
  ["No hay mal", "que dure cien años"],
  ["No hay mal", "que por bien no venga"],
  ["No hay rosa", "sin espinas"],
  ["Nunca digas", "de este agua no beberé"],
  ["Nunca es tarde", "si la dicha es buena"],
  ["Obras son amores", "y no buenas razones"],
  ["Ojos que no ven", "corazón que no siente"],
  ["Para muestra", "un botón"],
  ["Perro que ladra", "no muerde"],
  ["Poco a poco", "se anda lejos"],
  ["Por la boca", "muere el pez"],
  ["Preguntando", "se llega a Roma"],
  ["Quien mucho abarca", "poco aprieta"],
  ["Se dice el pecado", "más no el pecador"],
  ["Siempre pagan justos", "por pecadores"],
  ["Un clavo", "saca otro clavo"],
  ["Una golondrina", "no hace verano"],
  ["Zapatero", "a sus zapatos"],
];
